Feature/redis cache
benoitdm-oslandia/pg_featureserv pull request #132
Opened 2022-11-09 08:36 UTC by jmkerloch

related #89 

# `Cacher` interface
- update `AddWeakEtag` and `RemoveWeakEtag` function to return error
- :warning: for now if an error is returned, a message is displayed in log as a warning

# `CacheRedis` implementation of `Cacher`
- new implementation with use of a Redis server

# API
- `etag.go` : add `EtagToWeakEtag` function to mutualize code for `CacheRedis` and `CacheNaive`

# GitHub Action
- add redis service for `CacheRedis` tests

2022-11-09 16:11 UTC, jmkerloch commented on internal/data/cache_redis.go
> +	if err == redis.Nil {
Add comment for redis.Nil to indicate that it represents absence of value.

2022-11-09 16:12 UTC, jmkerloch commented on internal/data/cache_redis.go
> +	return nb_deleted == 1, err
safer to check for > 1 instead of ==1

2022-11-09 16:13 UTC, jmkerloch commented on internal/data/cache_redis.go
> +	return int(cache.client.DBSize(cache.ctx).Val())
in case of error return -1

2022-11-09 16:14 UTC, jmkerloch commented on internal/data/cache_test/cache_redis_test.go
> +		err := cache.Init("localhost:6379")
to be replaced by environnement variable

2022-11-16 15:34 UTC, benoitdm-oslandia requested changes

2022-11-16 15:34 UTC, benoitdm-oslandia commented on internal/api/etag.go
> +func EtagToWeakEtag(strongEtag string) (string, error) {
Add a comment on each new "exported" function please

2022-11-16 15:34 UTC, benoitdm-oslandia commented on internal/conf/config.go
> +func initNaiveCache() {
can you move this function and the next one to `cache_naive.go` and `cache_redis.go`? or it generates a dep cycle?

2022-11-16 16:23 UTC, jmkerloch commented on internal/conf/config.go
> +func initNaiveCache() {
it generates a dep cycle because I need to update conf.Configuration in initNaiveCache.

But I'm moving the function to NaiveCacheConfig and RedisCacheConfig struct. Same for initCache to Cache struct

2022-11-17 09:19 UTC, azarz commented on internal/conf/cacheconfig.go
> +func (cache *Cache) InitFromEnvVariables() {
The name of these methods is a bit confusing, since when no env var is set, the cache is initialized using the config file

2022-11-17 10:20 UTC, benoitdm-oslandia requested changes
Just need to rename the cache init functions!

2022-11-17 10:20 UTC, benoitdm-oslandia commented on internal/conf/cacheconfig.go
> +func (cache *Cache) InitFromEnvVariables() {
it could be replaced by `initFromConfig`?

2022-11-17 11:04 UTC, jmkerloch commented on internal/conf/cacheconfig.go
> +func (cache *Cache) InitFromEnvVariables() {
For me it's really doing the initialization from the environnement variable. No config file is used in these function.

The read of the config file is only done by viper.

2022-11-18 09:37 UTC, benoitdm-oslandia approved these changes, later dismissed
good to go

2022-11-18 10:47 UTC, benoitdm-oslandia approved these changes
go

2022-11-18 14:37 UTC, merged