fix(handler): requested format with Accept header and suffix
benoitdm-oslandia/pg_featureserv pull request #134
Opened 2022-11-10 09:36 UTC by nrevelant

2022-11-10 10:14 UTC, azarz requested changes

2022-11-10 10:14 UTC, azarz commented on internal/service/handler.go
>  	}
To remove: `err` is not what is tested here, and `errQuery` is checked line 460

2022-11-10 10:14 UTC, azarz commented on internal/service/mock_test/handler_get_test.go
> + Authors  : Nicolas Revelant (nicolas dot revelant at ign dot fr)
Add other authors too.

2022-11-14 14:27 UTC, benoitdm-oslandia requested changes

2022-11-14 14:27 UTC, benoitdm-oslandia commented on internal/service/mock_test/handler_get_test.go
> +		checkRouteWithAcceptHeader(t, "/api.html", htmlAccept, http.StatusOK, api.ContentTypeHTML)
we want the opposite: if the user specifies a suffix, it will supersed the header!

2022-11-14 14:27 UTC, benoitdm-oslandia commented on internal/api/net.go
>  	if hdrAcceptValue != "" {
we want the opposite: if the user specifies a suffix, it will supersed the header!

2022-11-14 14:27 UTC, benoitdm-oslandia commented on internal/service/handler.go
> +	addRoute(router, "/home", handleRoot)
is it necessary? It worked well before

2022-11-14 14:27 UTC, benoitdm-oslandia commented on internal/service/handler.go
>  	param.Filter = parseFilter(reqParam.Values, tbl.DbTypes)
must be in the `if errQuery == nil {` block

2022-11-14 14:27 UTC, benoitdm-oslandia commented on internal/service/mock_test/handler_get_test.go
> + Date     : September 2022
this is the creation date not the modification date

2022-11-16 09:23 UTC, nrevelant commented on internal/service/mock_test/handler_get_test.go
> +		checkRouteWithAcceptHeader(t, "/api.html", htmlAccept, http.StatusOK, api.ContentTypeHTML)
Ok done

2022-11-16 13:28 UTC, nrevelant commented on internal/service/mock_test/handler_get_test.go
> + Date     : September 2022
October 2022 according to the following command :
` git log --follow --format=%ad --date default internal/service/mock_test/handler_get_test.go`

2022-11-17 10:18 UTC, benoitdm-oslandia requested changes

2022-11-17 10:18 UTC, benoitdm-oslandia commented on internal/api/net.go
> +			return suffix
it will be better to return nil or empty string when we do not understand the suffix

2022-11-17 10:18 UTC, benoitdm-oslandia commented on internal/api/net.go
> +					return hdrAcceptValue
as we are in a loop, if we the current `mediaTypeValue` we should `continue` to analyse the other formats. At the end, if nothing is found and we quit the loop, we should return nil or empty string (when we do not understand the format)

2022-11-17 10:18 UTC, benoitdm-oslandia commented on internal/service/handler.go
> +	addRoute(router, "/home", handleRoot)
please remove it. We will fix the `.{fmt}` and `{.fmt}` in an other PR

2022-11-17 10:18 UTC, benoitdm-oslandia commented on internal/service/handler.go
> +	addRoute(router, "/index", handleRoot)
please remove it. We will fix the `.{fmt}` and `{.fmt}` in an other PR

2022-11-17 10:18 UTC, benoitdm-oslandia commented on internal/service/util.go
> +}
is it still used? or can we remove it?

2022-11-17 14:07 UTC, nrevelant commented on internal/api/net.go
> +			return suffix
The reason is the the format value is used by the handler functions, into the error message when the format value is not supported/unrecognized : 
`			return appErrorNotAcceptable(nil, api.ErrMsgNotSupportedFormat, format)`

2022-11-17 14:07 UTC, nrevelant commented on internal/api/net.go
> +					return hdrAcceptValue
The reason is the the format value is used by the handler functions, into the error message when the format value is not supported/unrecognized : 
`			return appErrorNotAcceptable(nil, api.ErrMsgNotSupportedFormat, format)`

2022-11-17 14:58 UTC, nick-rv commented on internal/service/util.go
> +}
`func getRequestVar(varName string, r *http.Request)` is now used to get a parameter value inside the URL elements
`func getRequestVarStrip(varName string, r *http.Request)` is dedicated to get a value from a parameter situated at the end of the URL (stripping the possible suffix)

2022-11-17 15:34 UTC, nrevelant commented on internal/api/net.go
> +					return hdrAcceptValue
OK, hdrAcceptValue is now returned outside the for loop, once all formats have been checked.

2022-11-18 13:25 UTC, benoitdm-oslandia approved these changes
you can merge

2022-11-18 16:01 UTC, azarz approved these changes

2022-11-18 16:03 UTC, merged