Feat/if none match
benoitdm-oslandia/pg_featureserv pull request #141
Opened 2022-11-24 08:59 UTC by nrevelant

Precondition headers management may be factorized.

But i suppose that the best way to do it may be found when other headers than if-none-match will be implemented ?

2022-11-24 09:20 UTC, azarz requested changes
Code factorisation needed

2022-11-26 09:56 UTC, benoitdm-oslandia requested changes

2022-11-26 09:56 UTC, benoitdm-oslandia commented on internal/data/catalog_db.go
> +	return true
could be replaced by a call to catalogInstance.GetCache().Reset(). You should not have Cacher implementation code outside Cacher implementations.

2022-11-26 09:56 UTC, benoitdm-oslandia commented on internal/data/catalog_db.go
> +			return true, err
`CheckStrongEtags` need to renamed as `IsOneEtagInCache` or something like that. Add a comment.

2022-11-26 09:56 UTC, benoitdm-oslandia commented on internal/service/handler.go
> +			w.WriteHeader(http.StatusNotModified) // weak etag detected into the cache
I will need more explanations for this part

2022-11-26 13:37 UTC, nrevelant commented on internal/service/handler.go
> +			w.WriteHeader(http.StatusNotModified) // weak etag detected into the cache
This has been done this way according to the RFC guidelines which describes the precondition evaluation method : https://www.rfc-editor.org/rfc/rfc7232.html#section-3

That way i think it is easier to evaluate the implementation of the RFC and to compare with the code.

For example : 
```
If the field-value is "*", the condition is false if the origin server does
   not have a current representation for the target resource.  If the
   field-value is a list of entity-tags, the condition is false if none
   of the listed tags match the entity-tag of the selected
   representation.
```

2022-11-27 22:09 UTC, nrevelant commented on internal/data/catalog_db.go
> +			return true, err
See https://github.com/benoitdm-oslandia/pg_featureserv/pull/141#discussion_r1032765938

2022-11-28 09:27 UTC, nrevelant commented on internal/data/catalog_db.go
> +	return true
I tried many different ways to do it.
Talking about golang, we seem to face interface, structures and pointers, but not class and object instances.
I think this issue may be managed in a future PR, trying to get a uniform implementation between single instance cache and shared Redis cache, don't you think ?

2022-11-29 07:55 UTC, benoitdm-oslandia commented
Rework, mock tests are OK. Need to review db tests

2022-12-07 09:21 UTC, jmkerloch commented on internal/data/listener.go
> +		_, err = listener.cache.AddWeakEtag(weakEtag.AlternateCacheKey(), weakEtag)
@benoitdm-oslandia the feature ID is not defined so AlternateCacheKey won't return a valid key.

2022-12-07 09:26 UTC, jmkerloch commented on internal/service/handler.go
> +		if checkPrecondition {
@benoitdm-oslandia could be only one if

2022-12-07 09:28 UTC, jmkerloch commented on internal/service/handler.go
> +	// TODO should not be here! What if the output format is html?
@benoitdm-oslandia as the comment says, they can be no cache if response is in JSON format.

2022-12-07 10:13 UTC, azarz approved these changes, later dismissed
LGTM, aside from jmkerloch's comments

2022-12-07 11:13 UTC, benoitdm-oslandia commented on internal/data/listener.go
> +		_, err = listener.cache.AddWeakEtag(weakEtag.AlternateCacheKey(), weakEtag)
fixed!

2022-12-07 11:24 UTC, benoitdm-oslandia commented on internal/service/handler.go
> +		if checkPrecondition {
done!

2022-12-07 13:14 UTC, benoitdm-oslandia commented on internal/service/handler.go
> +	// TODO should not be here! What if the output format is html?
done!

2022-12-07 13:49 UTC, benoitdm-oslandia approved these changes

2022-12-08 16:34 UTC, azarz approved these changes

2022-12-09 07:03 UTC, merged