WIP: Feature/crs
benoitdm-oslandia/pg_featureserv pull request #162
Opened 2023-02-08 11:32 UTC by azarz

closes #18 (already implemented)
closes #17

2023-02-13 08:49 UTC, benoitdm-oslandia commented on internal/data/catalog_db.go
> +		geomStr = fmt.Sprintf(", ST_Transform(ST_SetSRID(ST_GeomFromGeoJSON($%d), %s), 4326)", i, crs)
does it mean you only allow 4326 data in database?

2023-02-13 14:00 UTC, azarz commented on internal/data/catalog_db.go
> +		geomStr = fmt.Sprintf(", ST_Transform(ST_SetSRID(ST_GeomFromGeoJSON($%d), %s), 4326)", i, crs)
My bad, fixed in 0da771b.
We now use tbl.Srid (which I didn't know about before)

2023-02-13 14:14 UTC, benoitdm-oslandia requested changes
LGTM! Just if you can add a test with projection name like with EPSG:2154 or IGNF:LAMB93... this should do the same job!

2023-02-13 15:30 UTC, azarz commented
> LGTM! Just if you can add a test with projection name like with EPSG:2154 or IGNF:LAMB93... this should do the same job!

This would imply a change in the current API, which currently needs a number in the request, corresponding to the SRID in postGIS. An other issue is that the IGNF: SRSs are not available in postGIS...
I tried to find a standard definition of the IGNF:LAMB93 as in http://www.opengis.net/def/crs/EPSG/0/2154, IGNF is not even listed in http://www.opengis.net/def/crs/.

On way to tackle this issue would be to accept `proj` strings, but I don't know if this is a good idea...

2023-02-13 15:57 UTC, benoitdm-oslandia commented
Ok so no need to go further and we will update the documentation accordingly.

2023-02-13 17:13 UTC, azarz commented
We should also document that for POST, PUT and PATCH, the crs is defined by the `Content-Crs` header. I don't know where to specify that in the openApi definition.

2023-02-16 14:39 UTC, azarz commented
> We should also document that for POST, PUT and PATCH, the crs is defined by the `Content-Crs` header. I don't know where to specify that in the openApi definition.

Done

2023-02-17 08:40 UTC, benoitdm-oslandia approved these changes, later dismissed
LGTM

2023-02-17 08:51 UTC, jmkerloch submitted a review, later dismissed
LGTM

2023-02-17 13:21 UTC, azarz commented
New review required since I rebased on develop @jmkerloch @benoitdm-oslandia (I didn't change anything)

2023-02-17 13:22 UTC, jmkerloch approved these changes

2023-02-17 13:24 UTC, merged