Feat/geometry lod
benoitdm-oslandia/pg_featureserv pull request #172
Opened 2023-02-21 11:00 UTC by nrevelant

2023-02-21 15:10 UTC, benoitdm-oslandia requested changes
Still some minor corrections! Good job!

2023-02-21 15:10 UTC, benoitdm-oslandia commented on internal/data/feature_mock.go
> +func MakeFeatureMockPolygonAsJSON(tableName string, id int, coords orb.Ring, columns []string) string {
add comment to public function

2023-02-21 15:10 UTC, benoitdm-oslandia commented on internal/data/feature_mock.go
> +func MakeFeaturesMockPolygon(tableName string, val int, coords []orb.Ring) []*featureMock {
replace `val` by `id`

2023-02-21 15:10 UTC, benoitdm-oslandia commented on internal/data/feature_mock.go
> +		index++
you do not need to use `index` you can use `features = append(features, ...)`

2023-02-21 15:10 UTC, benoitdm-oslandia commented on internal/service/db_test/handler_db_lod_test.go
> +		rr := hTest.DoRequest(t, "/collections/mock_poly/items/6?max-allowable-offset=0.01")
can you first check this item has (without simplification) a 'big' geometry?

2023-02-21 15:10 UTC, benoitdm-oslandia commented on internal/service/db_test/handler_db_lod_test.go
> +		util.Equals(t, 4, len(feature.Geom.Geometry().(orb.Polygon)[0]), "wrong number of simplified coordinates")
can you just check the `len(v.Features) > 1` and then use a for loop to check all the feature of `v.Features`?

2023-02-21 15:10 UTC, benoitdm-oslandia commented on internal/service/db_test/handler_db_lod_test.go
> +		// If lower thant minVal, then minValue (0) is considered
typo: `than` not `thant`

Also, I think this choice must be discussed with the CrunchyData team. I tend to prefer an error like the `http.StatusBadRequest`

2023-02-21 15:10 UTC, benoitdm-oslandia commented on internal/service/db_test/handler_db_lod_test.go
> +		path = "/collections/mock_poly/items/4?max-allowable-offset=1"
May be returning an empty geometry should be considered as something not acceptable and should raise an error. To check with CrunchyData

2023-02-21 15:10 UTC, benoitdm-oslandia commented on internal/service/handler.go
> -
revert this change please

2023-02-21 15:10 UTC, benoitdm-oslandia commented on internal/service/param.go
> +	param.MaxAllowableOffset, err = parseFloat(paramValues, api.ParamMaxAllowableOffset, 0, 100000, 0)
do you have an explanation for the 100000 value?

2023-02-21 15:10 UTC, benoitdm-oslandia commented on internal/utiltest/test_db.go
>  	insertBytes := []byte(`
As sonarcloud suggests: we should extract this part in a dedicated function

2023-02-21 15:10 UTC, benoitdm-oslandia commented on internal/utiltest/test_db.go
> +	}
we should extract this part in a dedicated function

2023-02-21 15:11 UTC, benoitdm-oslandia commented
Last thing: can you add some documentation about how using this query parameter? What does it mean when a small value is used or a big one?

2023-02-22 09:21 UTC, nrevelant commented on internal/service/param.go
> +	param.MaxAllowableOffset, err = parseFloat(paramValues, api.ParamMaxAllowableOffset, 0, 100000, 0)
It has been chosen in an arbitrary manner.
I tend to consider that using more than 100000 meters or 100000 degrees can be considered as an upper limit.
But it seems i need some more opinions ?

2023-02-27 08:12 UTC, benoitdm-oslandia requested changes
Congrat! Only 4 remaining comments and we will merge!

2023-02-27 08:12 UTC, benoitdm-oslandia commented on internal/api/openapi.go
> +					Type:    "integer",
```suggestion
					Type:    "number",
```
ie. float

2023-02-27 08:12 UTC, benoitdm-oslandia commented on internal/utiltest/test_db.go
> +		geometryType string
You have created a `GeometryType` in `datatype.go`, can you use it here?

2023-02-27 08:14 UTC, benoitdm-oslandia commented on internal/service/db_test/handler_db_lod_test.go
> +		path = "/collections/mock_poly/items/4?max-allowable-offset=1"
@pramsey Do you have a preference?

2023-02-27 08:15 UTC, benoitdm-oslandia commented on internal/service/param.go
> +	param.MaxAllowableOffset, err = parseFloat(paramValues, api.ParamMaxAllowableOffset, 0, 100000, 0)
ok @nrevelant we keep it like that!

2023-02-28 08:47 UTC, benoitdm-oslandia approved these changes, later dismissed
We will wait a bit for CrunchyData before merging

2023-04-04 14:46 UTC, benoitdm-oslandia approved these changes

2023-04-04 14:46 UTC, benoitdm-oslandia approved these changes, later dismissed
LGTM

2023-04-04 14:47 UTC, benoitdm-oslandia commented on internal/service/db_test/handler_db_lod_test.go
> +		path = "/collections/mock_poly/items/4?max-allowable-offset=1"
may be later

2023-04-04 15:08 UTC, benoitdm-oslandia approved these changes

2023-04-04 15:09 UTC, merged